// Constants for random Indonesian names (30 Male, 30 Female)

export const PEJUANG_NAMES = [
  "Aji Saputra",
  "Bambang Wijaya",
  "Aldi Pratama",
  "Rian Hidayat",
  "Budi Santoso",
  "Denny Setiawan",
  "Fahri Ramadhan",
  "Guntur Wibowo",
  "Hendra Kusuma",
  "Indra Lesmana",
  "Joko Susilo",
  "Kevin Sanjaya",
  "Lukman Hakim",
  "Mifta Farid",
  "Nugroho Adhi",
  "Oki Nugraha",
  "Putu Gede",
  "Rizky Ramadhan",
  "Surya Kencana",
  "Taufik Hidayat",
  "Vicky Prasetyo",
  "Wahyu Hidayat",
  "Yuda Pratama",
  "Zaki Mubarak",
  "Bobby Nasution",
  "Dedi Sugandi",
  "Eko Prasetyo",
  "Farhan Halim",
  "Gilang Dirga",
  "Roni Gunawan",
  "Eka Saputra",
  "Dimas Prasetyo",
  "Bagus Wicaksono",
  "Teguh Riyadi",
  "Dwi Haryanto",
  "Rian Nugraha",
  "Agus Siswanto",
  "Deden Kusuma",
  "Slamet Rahardjo",
  "Kurniawan Dwi",
  "Mulyono Hadi",
  "Sutrisno Hartono",
  "Heru Triyono",
  "Rudi Hermawan",
  "Ade Permana",
  "Dani Ramdani",
  "Candra Wijaya",
  "Arya Kamandanu",
  "Galang Pratama",
  "Rangga Sasana"
];

export const PASANGAN_NAMES = [
  "Nisa Rahmawati",
  "Siti Aminah",
  "Amalia Putri",
  "Bella Cantika",
  "Citra Kirana",
  "Dian Sastrowardoyo",
  "Elsa Mayori",
  "Fitri Handayani",
  "Gita Gutawa",
  "Hesti Purwadinata",
  "Indah Permatasari",
  "Julia Perez",
  "Kartika Putri",
  "Lesti Kejora",
  "Mega Utami",
  "Nabila Syakieb",
  "Olivia Zalianty",
  "Prilly Latuconsina",
  "Queen Alexandra",
  "Rini Wulandari",
  "Siska Kohl",
  "Tari Nastiti",
  "Ussy Sulistiawaty",
  "Vanesha Prescilla",
  "Winda Citra",
  "Yuni Shara",
  "Zaskia Mecca",
  "Ayu Tingting",
  "Dewi Perssik",
  "Lulu Tobing",
  "Indah Lestari",
  "Ratih Purwasih",
  "Sri Wahyuni",
  "Dewi Lestari",
  "Kartini Mulya",
  "Siti Rahmawati",
  "Dona Amelia",
  "Ayu Lestari",
  "Ratna Sari",
  "Wulan Guritno",
  "Siska Kamila",
  "Eka Putri",
  "Fitria Rahayu",
  "Nining Suningsih",
  "Endang Suhartini",
  "Rina Nose",
  "Mila Karmila",
  "Ria Ricis",
  "Angel Lelga",
  "Gisella Anastasia",
  "Jessica Iskandar"
];

// Helper to choose unique pairs of character name and spouse name
// By exporting this stable evaluation, each page load will have its own unique set of names.
export function getRandomNames() {
  const maleShuffled = [...PEJUANG_NAMES].sort(() => Math.random() - 0.5);
  const femaleShuffled = [...PASANGAN_NAMES].sort(() => Math.random() - 0.5);

  return {
    pejuangMahar: maleShuffled[0],
    pasanganMahar: femaleShuffled[0],
    tulangPunggung: maleShuffled[1] || maleShuffled[0], // fallback if arrays are small
    pasanganKeluarga: femaleShuffled[1] || femaleShuffled[0],
  };
}

// Generate the names dynamically on load for this app instance
export const APP_SESSION_NAMES = getRandomNames();
